name: Test Katas

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ListKatas:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.kata_tests.outputs.tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List Katas to Test
        id: kata_tests
        working-directory: src/test/java/katas/exercises
        run: |
          kata_json=$(find . -name '*Test.java' | jq -R -s -c 'split("\n")[:-1]')
          echo "tests=$kata_json" >> $GITHUB_OUTPUT

  Test:
    needs: ListKatas
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kata_name: ${{ fromJson(needs.ListKatas.outputs.tests) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Run Unit Tests
        run: |
          echo "Testing file: ${{ matrix.kata_name }}"
          mvn -Dtest=${{ matrix.kata_name }} test

  StoreTestId:
    needs: Test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Store Run ID
        run: |
          git config --local user.email "java@katas"
          git config --local user.name "auto-test"
          git checkout -b internal/test || git checkout internal/test
          echo ${GITHUB_RUN_ID} > .test_results_id
          git add .test_results_id && git commit -m "Update run ID"
          git push origin internal/test --force
